### ISSUE TITLE
Importing NBO into ECOCORE

### ISSUE THREAD

**Issue by pbuttigieg** [obo-behavior/behavior-ontology#43]
Dear NBO team,

We've created an ontology for core ecological entities (ECOCORE) over at this [repo](https://github.com/EcologicalSemantics/ecocore/). 

We'll need ethology semantics and will be importing NBO. We'll likely have some requests for NBO - are you able to address these in the near-term? If not, we'll create some classes in ECOCORE and mark them as "to be surrendered to NBO" or similar, in anticipation of new class creation here.

Looking forward to developing!

**Comment by reality** [comment]
Hi, please let us know what terms you'd like added, and we'll get to them within 1-2 weeks :)

**Comment by pbuttigieg** [comment]
Hi @reality, 

We're active again at ECOCORE and have refreshed our imports for our release process. 
However, we're getting a parse error on NBO (output below).

Any insight? Is there some sort of encoding error?
The other ontologies we import through our OSK Makefile seem to work fine.


```
2018-07-29 20:09:55,550 ERROR (CommandRunner:4068) could not parse:http://purl.obolibrary.org/obo/nbo.owl
org.semanticweb.owlapi.io.UnparsableOntologyException: Problem parsing http://purl.obolibrary.org/obo/nbo.owl
Could not parse ontology.  Either a suitable parser could not be found, or parsing failed.  See parser logs below for explanation.
The following parsers were tried:
1) RDFXMLParser
2) OWLXMLParser
3) OWLFunctionalSyntaxOWLParser
4) TurtleOntologyParser
5) KRSS2OWLParser
6) ManchesterOWLSyntaxOntologyParser
7) OBOFormatOWLAPIParser


Detailed logs:
--------------------------------------------------------------------------------
Parser: RDFXMLParser
org.xml.sax.SAXParseException; systemId: http://purl.obolibrary.org/obo/nbo.owl; lineNumber: 549314; columnNumber: 47; Premature end of file.

--------------------------------------------------------------------------------
Parser: OWLXMLParser
Attribute not found: IRI (Line 53)

--------------------------------------------------------------------------------
Parser: OWLFunctionalSyntaxOWLParser
Encountered " <ERROR> "< "" at line 1, column 1.
Was expecting:
    "Ontology" ...
     (Line 0)

--------------------------------------------------------------------------------
Parser: TurtleOntologyParser
uk.ac.manchester.cs.owl.owlapi.turtle.parser.ParseException: Encountered "" at line 1, column 1.
Was expecting one of:


--------------------------------------------------------------------------------
Parser: KRSS2OWLParser
de.uulm.ecs.ai.owlapi.krssparser.ParseException: Encountered " ">" "<?xml version=\"1.0\"?> "" at line 1, column 1.
Was expecting:
    <EOF>


--------------------------------------------------------------------------------
Parser: ManchesterOWLSyntaxOntologyParser
Encountered '<?xml version="1.0"?>' at line 1 column 1.  Expected either 'Ontology:' or 'Prefix:' (Line 1)

--------------------------------------------------------------------------------
Parser: OBOFormatOWLAPIParser
LINENO: 1 - Could not find tag separator ':' in line.
LINE: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">


        at uk.ac.manchester.cs.owl.owlapi.ParsableOWLOntologyFactory.loadOWLOntology(ParsableOWLOntologyFactory.java:242)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:867)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:778)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:735)
        at owltools.io.ParserWrapper.parseOWL(ParserWrapper.java:172)
        at owltools.io.ParserWrapper.parseOWL(ParserWrapper.java:159)
        at owltools.io.ParserWrapper.parse(ParserWrapper.java:141)
        at owltools.cli.CommandRunner.runSingleIteration(CommandRunner.java:4056)
        at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:76)
        at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:68)
        at owltools.cli.CommandLineInterface.main(CommandLineInterface.java:12)
Makefile:42: recipe for target 'mirror/nbo.owl' failed
make: *** [mirror/nbo.owl] Error 1

```

**Comment by pbuttigieg** [comment]
Hi again,

Mysteriously, we were able to fix this by running the import target again. Not sure what happened or if it's really an issue.

**Comment by reality** [comment]
Looks like it was probably a temporary failure to download the ontology? Please re-open the issue if it continues to be a problem!
